name: sodium
description: Sodium mangement application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: "^1.3.5"
  charts_flutter: ^0.4.0
  flutter_circular_chart: ^0.1.0
  dio: ^1.0.6
  rxdart: ^0.19.0
  shared_preferences: ^0.4.3
  fluttertoast: ^2.0.9
  font_awesome_flutter: ^8.1.0
  after_layout: ^1.0.7
  percent_indicator: "^1.0.10"
  shimmer: ^0.0.6
  flutter_redux: ^0.5.2
  redux: ^3.0.0
  redux_remote_devtools: ^0.0.5
  month_picker_strip: ^0.0.3
  date_util: ^0.1.4
  clippy_flutter: ^1.0.0
  flutter_calendar: 0.0.7
  modal_drawer_handle: ^1.0.3
  rounded_modal: ^1.0.0
  zefyr: ^0.3.0
  firebase_storage: ^1.0.4
  image: ^2.0.5
  path_provider: ^0.4.1
  cached_network_image: ^0.5.1
  flutter_cupertino_date_picker: ^0.3.0
  numberpicker: ^0.1.7
  flutter_svg: ^0.8.2
  flutter_local_notifications: ^0.4.2+1
  wave: ^0.0.8

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  test: ^1.5.1
  mockito: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "asset/icon/sodium_bottle.png"
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/sodium_male.png
     - asset/blood_pressure_male.png
     - asset/blood_pressure_close_up.png
     - asset/logo/camt.png
     - asset/logo/cmu.png
     - asset/logo/nursing.png
     - asset/logo/nrct.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/custom_icons.ttf
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Black.ttf
          weight: 900
        - asset: fonts/Kanit-ExtraBold.ttf
          weight: 800
        - asset: fonts/Kanit-Bold.ttf
          weight: 700
        - asset: fonts/Kanit-Semibold.ttf
          weight: 600
        - asset: fonts/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit-Regular.ttf
          weight: 400
        - asset: fonts/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit-Light.ttf
          weight: 200
        - asset: fonts/Kanit-Thin.ttf
          weight: 100
